CREATE SCHEMA IF NOT EXISTS control;
SET SCHEMA control;

CREATE TABLE IF NOT EXISTS definition_version (
    definition_id VARCHAR(120) NOT NULL,
    version INTEGER NOT NULL,
    fingerprint CHAR(64) NOT NULL,
    parent_fingerprint CHAR(64),
    title VARCHAR(240) NOT NULL,
    content CLOB NOT NULL,
    rule_version VARCHAR(80) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (definition_id, version),
    UNIQUE (fingerprint)
);

CREATE TABLE IF NOT EXISTS migration_run (
    id CHAR(36) NOT NULL PRIMARY KEY,
    definition_id VARCHAR(120) NOT NULL,
    fingerprint CHAR(64) NOT NULL,
    rule_version VARCHAR(80) NOT NULL,
    name VARCHAR(180) NOT NULL,
    schema_name VARCHAR(120) NOT NULL,
    status VARCHAR(40) NOT NULL,
    failure_arm VARCHAR(240),
    exit_mode VARCHAR(20),
    current_step VARCHAR(120),
    cursor_id BIGINT,
    diagnosis CLOB,
    base_snapshot_fingerprint CHAR(64),
    started_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS run_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id CHAR(36) NOT NULL,
    seq INTEGER NOT NULL,
    event_type VARCHAR(80) NOT NULL,
    step_id VARCHAR(120),
    phase VARCHAR(80),
    previous_checksum CHAR(64),
    checksum CHAR(64) NOT NULL,
    payload CLOB NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (run_id, seq)
);

CREATE TABLE IF NOT EXISTS batch_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id CHAR(36) NOT NULL,
    step_id VARCHAR(120) NOT NULL,
    batch_no INTEGER NOT NULL,
    last_id BIGINT,
    source_rows INTEGER NOT NULL,
    inserted_rows INTEGER NOT NULL,
    checksum CHAR(64) NOT NULL,
    state VARCHAR(30) NOT NULL,
    recovered BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (run_id, step_id, batch_no)
);

CREATE TABLE IF NOT EXISTS verification_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id CHAR(36) NOT NULL,
    step_id VARCHAR(120) NOT NULL,
    verification_type VARCHAR(60) NOT NULL,
    status VARCHAR(30) NOT NULL,
    summary VARCHAR(500),
    detail CLOB NOT NULL,
    rule_version VARCHAR(80) NOT NULL,
    source_fingerprint CHAR(64) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS rehearsal_suite (
    id CHAR(36) NOT NULL PRIMARY KEY,
    definition_id VARCHAR(120) NOT NULL,
    fingerprint CHAR(64) NOT NULL,
    rule_version VARCHAR(80) NOT NULL,
    status VARCHAR(30) NOT NULL,
    summary CLOB NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS evidence_bundle (
    id CHAR(36) NOT NULL PRIMARY KEY,
    received_sha256 CHAR(64) NOT NULL UNIQUE,
    raw_json CLOB NOT NULL,
    kind VARCHAR(80),
    analysis_status VARCHAR(30) NOT NULL,
    analysis CLOB,
    rule_version VARCHAR(80),
    source_fingerprint CHAR(64),
    received_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
