package local.migrationlab.engine;

import com.fasterxml.jackson.databind.JsonNode;
import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.Instant;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import local.migrationlab.support.Sandbox;
import org.springframework.stereotype.Component;

@Component
public class PhysicalMigrator {
    private final Sandbox sandbox;

    public PhysicalMigrator(Sandbox sandbox) {
        this.sandbox = sandbox;
    }

    public void initializeSandbox(String schema, JsonNode definition) {
        try (Connection bootstrap = sandbox.bootstrapConnection();
             Statement createSchema = bootstrap.createStatement()) {
            createSchema.execute("create schema if not exists " + schema);
            bootstrap.commit();
        } catch (SQLException e) {
            throw new IllegalStateException("Sandbox schema creation failed", e);
        }
        try (Connection connection = sandbox.connection(schema); Statement statement = connection.createStatement()) {
            statement.execute("create schema if not exists " + schema);
            statement.execute("drop table if exists " + schema + ".customers_v2");
            statement.execute("drop trigger if exists trg_customers_dualwrite");
            statement.execute("drop table if exists " + schema + ".customers");
            statement.execute("""
                    create table %s.customers (
                        id bigint generated by default as identity primary key,
                        email varchar(320) not null,
                        created_at timestamp with time zone not null
                    )
                    """.formatted(schema, schema));
            int rows = definition.path("seedRows").asInt(137);
            try (PreparedStatement insert = connection.prepareStatement(
                    "insert into " + schema + ".customers (email, created_at) values (?, ?)")) {
                for (int i = 1; i <= rows; i++) {
                    insert.setString(1, "User" + i + "@Example.COM");
                    insert.setObject(2, java.sql.Timestamp.from(Instant.parse("2026-01-01T00:00:00Z").plusSeconds(i)));
                    insert.addBatch();
                    if (i % 50 == 0) {
                        insert.executeBatch();
                    }
                }
                insert.executeBatch();
            }
            connection.commit();
        } catch (SQLException e) {
            throw new IllegalStateException("Sandbox initialization failed", e);
        }
    }

    public boolean tableExists(Connection connection, String schema, String table) throws SQLException {
        DatabaseMetaData metaData = connection.getMetaData();
        try (ResultSet rs = metaData.getTables(null, null, table.toUpperCase(), new String[]{"TABLE", "VIEW"})) {
            boolean matched = false;
            while (rs.next()) {
                if (schema.equalsIgnoreCase(rs.getString("TABLE_SCHEM"))) {
                    matched = true;
                }
            }
            if (matched) {
                return true;
            }
        }
        try (PreparedStatement statement = connection.prepareStatement("""
                select 1 from information_schema.tables
                where lower(table_schema) = lower(?) and lower(table_name) = lower(?)
                """)) {
            statement.setString(1, schema);
            statement.setString(2, table);
            try (ResultSet fallback = statement.executeQuery()) {
                if (fallback.next()) {
                    return true;
                }
            }
        }
        try (ResultSet rs = metaData.getTables(null, schema, table, new String[]{"TABLE", "VIEW"})) {
            return rs.next();
        }
    }

    public boolean triggerExists(Connection connection, String schema, String name) throws SQLException {
        try (PreparedStatement statement = connection.prepareStatement("""
                select 1 from information_schema.triggers
                where lower(trigger_schema) = lower(?) and lower(trigger_name) = lower(?)
                """)) {
            statement.setString(1, schema);
            statement.setString(2, name);
            return statement.executeQuery().next();
        }
    }

    public long count(Connection connection, String schema, String table) throws SQLException {
        try (Statement statement = connection.createStatement();
             ResultSet rs = statement.executeQuery("select count(*) from " + schema + "." + table)) {
            rs.next();
            return rs.getLong(1);
        }
    }

    public long maxId(Connection connection, String schema, String table) throws SQLException {
        try (Statement statement = connection.createStatement();
             ResultSet rs = statement.executeQuery("select coalesce(max(id), 0) from " + schema + "." + table)) {
            rs.next();
            return rs.getLong(1);
        }
    }

    public long firstSourceIdMissingInTarget(Connection connection, String schema) throws SQLException {
        try (Statement statement = connection.createStatement();
             ResultSet rs = statement.executeQuery("""
                     select min(s.id)
                     from %s.customers s
                     left join %s.customers_v2 t on t.id = s.id
                     where t.id is null
                     """.formatted(schema, schema))) {
            rs.next();
            long value = rs.getLong(1);
            return rs.wasNull() ? Long.MAX_VALUE : value;
        }
    }

    public int batchNumberForCursor(long cursor, int batchSize) {
        if (cursor <= 0) {
            return 1;
        }
        return (int) Math.ceil((double) cursor / batchSize) + 1;
    }

    public void createTarget(Connection connection, String schema) throws SQLException {
        try (Statement statement = connection.createStatement()) {
            statement.execute("""
                    create table %s.customers_v2 (
                        id bigint primary key,
                        email varchar(320) not null,
                        email_normalized varchar(320) generated always as (lower(trim(email))) not null,
                        created_at timestamp with time zone not null
                    )
                    """.formatted(schema, schema));
        }
    }

    public void createDualWriteTrigger(Connection connection, String schema) throws SQLException {
        try (Statement statement = connection.createStatement()) {
            statement.execute("""
                    create trigger %s.trg_customers_dualwrite
                    after insert on %s.customers
                    for each row call "local.migrationlab.engine.DualWriteTrigger"
                    """.formatted(schema, schema));
        }
    }

    public void dropTrigger(Connection connection, String schema) throws SQLException {
        try (Statement statement = connection.createStatement()) {
            statement.execute("drop trigger if exists " + schema + ".trg_customers_dualwrite");
        }
    }

    public void cutover(Connection connection, String schema) throws SQLException {
        try (Statement statement = connection.createStatement()) {
            dropTrigger(connection, schema);
            statement.execute("alter table " + schema + ".customers rename to customers_old");
            statement.execute("alter table " + schema + ".customers_v2 rename to customers");
        }
    }

    public void reverseCutover(Connection connection, String schema) throws SQLException {
        try (Statement statement = connection.createStatement()) {
            dropTrigger(connection, schema);
            statement.execute("alter table " + schema + ".customers rename to customers_v2");
            statement.execute("alter table " + schema + ".customers_old rename to customers");
            statement.execute("""
                    create trigger %s.trg_customers_dualwrite
                    after insert on %s.customers
                    for each row call "local.migrationlab.engine.DualWriteTrigger"
                    """.formatted(schema, schema));
        }
    }

    public void dropTarget(Connection connection, String schema) throws SQLException {
        try (Statement statement = connection.createStatement()) {
            statement.execute("drop table if exists " + schema + ".customers_v2");
        }
    }

    public BatchResult backfillBatch(Connection connection, String schema, long cursor, int batchSize) throws SQLException {
        List<Map<String, Object>> rows = new ArrayList<>();
        try (PreparedStatement query = connection.prepareStatement("""
                select id, email, created_at from %s.customers
                where id > ? order by id fetch first %d rows only
                """.formatted(schema, batchSize))) {
            query.setLong(1, cursor);
            try (ResultSet rs = query.executeQuery()) {
                while (rs.next()) {
                    Map<String, Object> row = new LinkedHashMap<>();
                    row.put("id", rs.getLong(1));
                    row.put("email", rs.getString(2));
                    row.put("created_at", rs.getObject(3, java.time.OffsetDateTime.class));
                    row.put("created_at_text", String.valueOf(rs.getObject(3)));
                    rows.add(row);
                }
            }
        }
        int inserted = 0;
        try (PreparedStatement insert = connection.prepareStatement("""
                insert into %s.customers_v2 (id, email, created_at)
                select ?, ?, ?
                where not exists (select 1 from %s.customers_v2 where id = ?)
                """.formatted(schema, schema))) {
            for (Map<String, Object> row : rows) {
                long id = ((Number) row.get("id")).longValue();
                insert.setLong(1, id);
                insert.setString(2, (String) row.get("email"));
                insert.setObject(3, row.get("created_at"));
                insert.setLong(4, id);
                inserted += insert.executeUpdate();
            }
        }
        long lastId = cursor;
        if (!rows.isEmpty()) {
            lastId = ((Number) rows.get(rows.size() - 1).get("id")).longValue();
        }
        List<String> lines = rows.stream()
                .map(row -> row.get("id") + "|" + row.get("email") + "|" + row.get("created_at_text"))
                .toList();
        String checksum = local.migrationlab.support.Json.sha256(String.join("\n", lines));
        return new BatchResult(rows.size(), inserted, lastId, rows.isEmpty() || rows.size() < batchSize, checksum);
    }

    public List<List<Object>> readPath(Connection connection, String schema, String table) throws SQLException {
        List<List<Object>> rows = new ArrayList<>();
        try (Statement statement = connection.createStatement();
             ResultSet rs = statement.executeQuery(
                     "select id, email, created_at from " + schema + "." + table + " order by id")) {
            while (rs.next()) {
                rows.add(List.of(rs.getLong(1), rs.getString(2), String.valueOf(rs.getObject(3))));
            }
        }
        return rows;
    }

    public void insertSource(Connection connection, String schema, String email) throws SQLException {
        try (PreparedStatement statement = connection.prepareStatement(
                "insert into " + schema + ".customers (email, created_at) values (?, ?)")) {
            statement.setString(1, email);
            statement.setObject(2, java.sql.Timestamp.from(Instant.now()));
            statement.executeUpdate();
        }
    }

    public record BatchResult(int sourceRows, int insertedRows, long lastId, boolean complete, String checksum) {
    }
}
